### ISSUE TITLE
Feature: Additional AE fields

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm.mapping#35]
## Feature Details
We need these for gsm.ae. I'm including additional information to help set them up for gsm.datasim as well, plus future information for #7 in case we ever sort that out.
```yaml
    aeongo:
      type: character
      label: Ongoing
      values: "ONGOING", "" (which should encode as "NOT ONGOING")
    aerel:
      type: character
      label: Relatedness
      values: "NOT RELATED", "RELATED"
    mincreated_dts:
      type: timestamp
      label: Minimum Created Time
```

As far as I can find, this is everything that's needed in AE for the current iteration of gsm.ae.
