### ISSUE TITLE
Feature: Expand AE.yaml

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm.mapping#6]
This is what I'm currently using in {gsm.app} for AE (everything other than `subjid` and `aeser` are new):
```yaml
meta:
  Type: Mapped
  ID: AE
  Description: Adverse Event Data Mapping
  Priority: 1
spec:
  Raw_AE:
    subjid:
      type: character
    aeser:
      type: character
    aest_dt:
      type: Date
    aeen_dt:
      type: Date
    mdrpt_nsv:
      type: character
    mdrsoc_nsv:
      type: character
    aetoxgr:
      type: character
steps:
  - output: Mapped_AE
    name: =
    params:
      lhs: Mapped_AE
      rhs: Raw_AE
```
Ideally we'd also pull in `firstparticipantdate` from `Mapped_SUBJ` (see #5), and then calculate `aest_dy = aest_dt - firstparticipantdate` and `aeen_dt = aeen_dt - firstparticipantdate`, but I can calculate those myself if they don't make it into the "canonical" table.
